name: Run Pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 降级为v3，Gitee兼容
      - name: Set up Python
        uses: actions/setup-python@v3  # 降级为v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install pytest requests pytest-html python-dotenv tenacity
      - name: Run tests
        run: |
          pytest test_login_token.py --html=report.html --self-contained-html
      - name: Upload report
        uses: actions/upload-artifact@v3  # 降级为v3
        with:
          name: test-report
          path: report.html